baseURL = 'https://sentimental.pics'
languageCode = 'en-us'
title = "it's me you know"
theme = 'gallery'
timeout = 150
copyright = '© 2024 Jason Lo'

[markup.goldmark.renderer]
unsafe = true

[outputFormats]
  [outputFormats.photos]
    mediatype = "application/rss+xml"
    rel = "alternate"
    baseName = "photos"
    isHTML = false
    IsPlainText = false
    noUgly = true

[outputs]
  home = ['html', 'rss', 'photos']

[params]
  dateFormat = "January 02, 2006"
  [params.author]
    email = 'contact@sentimental.blue'
    name = 'Jason Lo'

[menus]
  [[menus.footer]]
    name = 'About Me/Contact'
    url = '/about-me'
    weight = 100
  [[menus.footer]]
    name = 'Link RSS'
    url = '/index.xml'
    weight = 100
  [[menus.footer]]
    name = 'Full Image RSS'
    url = '/photos.xml'
    weight = 100